import {renewalFeeToken} from '../../lib/membership-fees';
import {MembershipPrice} from '../membership-price';

import {uiText} from '../../lib/ui-text';
import {getLanguage as getUiLanguage} from '../language';
import {getLanguage} from '../language';
import {RenewalForm} from './form';
import '../shop/shop.css';
export const metadata={title:'Renew membership | KPKMM'};
export const dynamic='force-dynamic';
export default async function Renew(){
 const ui = uiText(await getUiLanguage());

 const bm=(await getLanguage())==='ms',t=(en:string,ms:string)=>bm?ms:en;
 const pricing=await renewalFeeToken();
 const year=Number(new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'Asia/Kuala_Lumpur'}).format(new Date()));
 return <main className="shop" style={{maxWidth:800}}><p className="eyebrow">KPKMM</p><h1>{t('Renew your membership','Perbaharui keahlian anda')}</h1><p>{t('Use your registered name OR MyKad/passport number. No need to re-enter your email, mobile number or address.','Gunakan nama berdaftar ATAU nombor MyKad/pasport. Tidak perlu memasukkan semula e-mel, nombor telefon atau alamat.')}</p>
 <section className="shop-note"><h2>{t('Before you pay','Sebelum membayar')}</h2><p>{t('Your membership number is permanent, even while inactive. If your last active year is more than one year ago, you must contact the committee for manual reinstatement. Only existing members with a matching database record can renew. Contact the club before paying if your record needs correcting or your last active year is unknown.','Nombor ahli anda kekal walaupun tidak aktif. Jika tahun aktif terakhir melebihi setahun lalu, hubungi jawatankuasa untuk pengaktifan semula secara manual. Hanya ahli sedia ada dengan rekod pangkalan data yang sepadan boleh memperbaharui. Hubungi kelab sebelum membayar jika rekod perlu dibetulkan atau tahun aktif terakhir tidak diketahui.')}</p><a href="tel:+60182262000">018-226 2000</a></section><section className="shop-card"><h2>{t('Annual renewal','Pembaharuan tahunan')}</h2><MembershipPrice quote={pricing.quote} bm={bm}/><p>{t('No additional administrative fee. See the joining page for new-member pricing.','Tiada yuran pentadbiran tambahan. Lihat halaman permohonan untuk yuran ahli baharu.')} <a href="/join">{t('New member application →','Permohonan ahli baharu →')}</a></p><div className="bank-details"><strong>Maybank</strong><span>Kelab Peminat Kereta Mini Malaysia</span><strong style={{fontSize:'1.5rem'}}>5123 4360 5508</strong></div><p>{t('Transfer the total payable shown above to the club account, then attach your payment proof below. Submission is not approval or confirmation of payment.','Pindahkan jumlah perlu dibayar di atas ke akaun kelab, kemudian lampirkan bukti bayaran di bawah. Penghantaran bukan kelulusan atau pengesahan bayaran.')}</p></section>
 <p>{t('This fee quote is valid for 24 hours.','Sebut harga ini sah selama 24 jam.')}</p><section className="shop-card"><h2>{t('Your renewal details','Maklumat pembaharuan anda')}</h2><p>{t('Use either your full registered name or your MyKad/passport number. Capital letters and extra spaces do not matter. If a name matches more than one member, use your identification number. Unmatched entries cannot renew.','Gunakan nama penuh berdaftar atau nombor MyKad/pasport. Huruf besar dan ruang tambahan tidak menjejaskan padanan. Jika nama sepadan dengan lebih daripada seorang ahli, gunakan nombor pengenalan. Maklumat yang tidak sepadan tidak boleh memperbaharui.')}</p><RenewalForm bm={bm} year={year} feeToken={pricing.token}/></section>
 <section className="shop-note"><h2>{t('Privacy and review','Privasi dan semakan')}</h2><p>{t('Your existing member details and payment proof are stored privately for authorised KPKMM administrators and emailed through Google Gmail to kelabpeminatkeretaminimalaysia@gmail.com to verify your renewal. They are not published on this website. Do not include another person’s information.','Maklumat ahli sedia ada dan bukti bayaran anda disimpan secara sulit untuk pentadbir KPKMM yang dibenarkan dan dihantar melalui Google Gmail ke kelabpeminatkeretaminimalaysia@gmail.com bagi pengesahan pembaharuan. Maklumat tidak diterbitkan di laman ini. Jangan sertakan maklumat orang lain.')}</p><p>{t('Stored personal details are not shown when searching by name or identification number. Requests remain pending until the committee verifies payment. For record corrections, withdrawal or privacy questions, contact','Maklumat peribadi yang disimpan tidak dipaparkan semasa carian nama atau nombor pengenalan. Permohonan menunggu jawatankuasa mengesahkan bayaran. Untuk pembetulan rekod, penarikan atau pertanyaan privasi, hubungi')} <a href="mailto:kelabpeminatkeretaminimalaysia@gmail.com">kelabpeminatkeretaminimalaysia@gmail.com</a> / <a href="tel:+60182262000">018-226 2000</a>.</p></section></main>;
}
