
import {uiText} from '../../lib/ui-text';
import {getLanguage as getUiLanguage} from '../language';
import {getLanguage} from '../language';
import {RenewalForm} from './form';
import '../shop/shop.css';
export const metadata={title:'Renew membership | KPKMM'};
export const dynamic='force-dynamic';
export default async function Renew(){
 const ui = uiText(await getUiLanguage());

 const bm=(await getLanguage())==='ms',t=(en:string,ms:string)=>bm?ms:en;
 const year=Number(new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'Asia/Kuala_Lumpur'}).format(new Date()));
 return <main className="shop" style={{maxWidth:800}}><p className="eyebrow">KPKMM</p><h1>{t('Renew your membership','Perbaharui keahlian anda')}</h1><p>{t('For existing members. Submit your updated details and transfer receipt for club verification.','Untuk ahli sedia ada. Hantar maklumat terkini dan resit pindahan untuk pengesahan kelab.')}</p>
 <section className="shop-note"><h2>{t('Before you pay','Sebelum membayar')}</h2><p>{t('Your membership number is permanent, even while inactive. If your last active year is more than one year ago, you must contact the committee for manual reinstatement. If your identity details or last active year are missing from our records, contact the club before paying.','Nombor ahli anda kekal walaupun tidak aktif. Jika tahun aktif terakhir melebihi setahun lalu, hubungi jawatankuasa untuk pengaktifan semula secara manual. Jika maklumat pengenalan atau tahun aktif terakhir tiada dalam rekod, hubungi kelab sebelum membayar.')}</p><a href="tel:+60182262000">018-226 2000</a></section><section className="shop-card"><h2>{t('Annual renewal','Pembaharuan tahunan')} · RM150</h2><p>{t('No additional administrative fee. New members: RM250 for the first year.','Tiada yuran pentadbiran tambahan. Ahli baharu: RM250 untuk tahun pertama.')} <a href="/join">{t('New member application →','Permohonan ahli baharu →')}</a></p><div className="bank-details"><strong>Maybank</strong><span>Kelab Peminat Kereta Mini Malaysia</span><strong style={{fontSize:'1.5rem'}}>5123 4360 5508</strong></div><p>{t('Transfer RM150 to the club account, then attach your payment proof below. Submission is not approval or confirmation of payment.','Pindahkan RM150 ke akaun kelab, kemudian lampirkan bukti bayaran di bawah. Penghantaran bukan kelulusan atau pengesahan bayaran.')}</p></section>
 <section className="shop-card"><h2>{t('Your renewal details','Maklumat pembaharuan anda')}</h2><p>{t('Your full name and MyKad/passport must match the same registered member. Capital letters and extra spaces do not matter. If your record needs correcting, contact the committee before paying.','Nama penuh dan MyKad/pasport mesti sepadan dengan rekod ahli berdaftar yang sama. Huruf besar dan ruang tambahan tidak menjejaskan padanan. Jika rekod perlu dibetulkan, hubungi jawatankuasa sebelum membayar.')}</p><RenewalForm bm={bm} year={year}/></section>
 <section className="shop-note"><h2>{t('Privacy and review','Privasi dan semakan')}</h2><p>{t('Your identification number, contact details, mailing address and payment proof are stored privately for authorised KPKMM administrators and emailed through Google Gmail to kelabpeminatkeretaminimalaysia@gmail.com to verify your renewal. They are not published on this website. Do not include another person’s information.','Nombor pengenalan, maklumat hubungan, alamat surat-menyurat dan bukti bayaran disimpan secara sulit untuk pentadbir KPKMM yang dibenarkan dan dihantar melalui Google Gmail ke kelabpeminatkeretaminimalaysia@gmail.com bagi pengesahan pembaharuan. Maklumat tidak diterbitkan di laman ini. Jangan sertakan maklumat orang lain.')}</p><p>{t('All fields are needed to process your request. For corrections, withdrawal or privacy questions, contact','Semua medan diperlukan untuk memproses permohonan. Untuk pembetulan, penarikan atau pertanyaan privasi, hubungi')} <a href="mailto:kelabpeminatkeretaminimalaysia@gmail.com">kelabpeminatkeretaminimalaysia@gmail.com</a> / <a href="tel:+60182262000">018-226 2000</a>.</p></section></main>;
}
