const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
function load(file,mocks){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>n.endsWith('/membership-fees')||n.endsWith('/membership-pricing')?require('./fee-fixture.cjs')(n):n==='../../lib/roster'?{nameKey:v=>'name:'+v}:n in mocks?mocks[n]:require(n),Buffer,FormData,File,Intl,Date});return exports;}
const normalizeName=s=>s.normalize('NFKC').trim().replace(/\s+/g,' ').toUpperCase(),nameKey=s=>'name:'+normalizeName(s);
let records=[],last=2026,online='review',dbFails=false;
const person={memberNumber:'B-09-001',name:'Sample Member',identity:'900101101234',email:'saved@example.invalid',phone:'saved phone',address:'saved address',addressLine:'saved street',postcode:'12345',state:'Selangor',mailingCountry:'Malaysia'};
const row=(member=person,year=2026)=>({member_number:member.memberNumber,membership_year:year,identity_hash:member.identity?'identity:'+member.identity:null,name_hash:nameKey(member.name),payload:JSON.stringify(member)});
const sql=async(parts,...v)=>{const q=parts.join('?');if(dbFails)throw Error('offline');if(q.startsWith('SELECT active'))return records.filter(r=>r.member_number===v[0]&&r.membership_year===v[1]).map(r=>({active:!!r.active}));if(q.includes('max(membership_year)'))return [{year:last}];
 const latest=new Map();for(const r of records.filter(x=>x.membership_year<=v[0]).sort((a,b)=>b.membership_year-a.membership_year))if(!latest.has(r.member_number))latest.set(r.member_number,r);
 if(q.includes('WHERE name_hash=')){assert.match(q,/AS latest/);return [...latest.values()].filter(r=>r.name_hash===v[1]).slice(0,3);}assert.match(q,/DISTINCT ON\(member_number\)/);return [...latest.values()];};
const lookupLib=load('lib/renewal-member.ts',{'./shop':{db:()=>sql},'./roster':{nameKey,normalizeName,rosterReady:async()=>{},renewalEligibility:async()=>online},'./renewals':{openRenewal:s=>s,renewalHash:s=>s}});
const lookup=(mode,value)=>{const f=new FormData();f.set('lookupMode',mode);f.set('lookupValue',value);return lookupLib.renewalLookup(f);};
let writes=[],mails=0,proofReads=0,limited=false,conflict=false,language='en';
const actionSql=async(p,...v)=>{const q=p.join('?');if(q.startsWith('LOCK'))return [];if(q.startsWith('SELECT payload'))return records;if(q.startsWith('UPDATE club_renewals')){assert.equal(v[0],15000);return [];}writes.push(v);return conflict?[]:[{id:'test-reference'}];};actionSql.begin=fn=>fn(actionSql);
const action=load('app/renew/actions.ts',{'next/headers':{headers:async()=>({get:()=>null})},'next/cache':{revalidatePath:()=>{}},'../language':{getLanguage:async()=>language},'../../lib/shop':{db:()=>actionSql,readImage:async file=>{proofReads++;if(file.type!=='image/png')throw Error('invalid');return {bytes:Buffer.from('test proof'),type:'image/png'};}},'../../lib/renewal-member':lookupLib,'../../lib/renewals':{renewalsReady:async()=>{},renewalLimit:async()=>!limited,sealRenewal:s=>s,openRenewal:s=>s,deliverRenewal:async()=>{mails++;return 'accepted';}}});
const form=(mode='name',value='Sample Member')=>{const f=new FormData();f.set('lookupMode',mode);f.set('lookupValue',value);f.set('consent','yes');f.set('year',new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'Asia/Kuala_Lumpur'}).format(new Date()));f.set('proof',new File(['mock proof'],'proof.png',{type:'image/png'}));return f;};
async function blocked(f,pattern){const before=[writes.length,mails,proofReads];const r=await action.requestRenewal({},f);assert.match(r.error,pattern);assert.deepEqual([writes.length,mails,proofReads],before);assert.deepEqual(Object.keys(r),['error']);}
(async()=>{
 assert.throws(()=>lookup('other','Sample Member'));assert.throws(()=>lookup('name','x'));assert.throws(()=>lookup('identity','!invalid'));
 records=[row()];assert.equal((await lookupLib.findRenewalMember(lookup('name',' sample   MEMBER '),2026,2026)).status,'eligible');assert.equal((await lookupLib.findRenewalMember(lookup('identity','900101-10-1234'),2026,2026)).status,'eligible');
 assert.equal((await lookupLib.findRenewalMember(lookup('name','Wrong Member'),2026,2026)).status,'missing');assert.equal((await lookupLib.findRenewalMember(lookup('identity','900101101235'),2026,2026)).status,'missing');
 records=[row(),row({...person,name:'Corrected Name',identity:'900101101235'},2027)];assert.equal((await lookupLib.findRenewalMember(lookup('name','Sample Member'),2026,2026)).status,'eligible');assert.equal((await lookupLib.findRenewalMember(lookup('name','Sample Member'),2027,2027)).status,'missing');assert.equal((await lookupLib.findRenewalMember(lookup('identity','900101101234'),2027,2027)).status,'missing');
 records=[row(),row({...person,memberNumber:'B-09-002'})];assert.equal((await lookupLib.findRenewalMember(lookup('name','Sample Member'),2026,2026)).status,'ambiguous');assert.equal((await lookupLib.findRenewalMember(lookup('identity','900101101234'),2026,2026)).status,'ambiguous');
 records=[row({...person,identity:'AB-12345',identityType:'passport',country:'Test Country'})];assert.equal((await lookupLib.findRenewalMember(lookup('identity','ab-12345'),2026,2026)).status,'eligible');
 records=[row({...person,identity:'',email:'',phone:'',address:''})];const legacy=await lookupLib.findRenewalMember(lookup('name','Sample Member'),2026,2026);assert.equal(legacy.status,'eligible');assert.equal(legacy.details.rosterMemberNumber,'B-09-001');assert.equal(legacy.identityHash,'roster-member:B-09-001');
 last=2024;assert.equal((await lookupLib.findRenewalMember(lookup('name','Sample Member'),2026,2026)).status,'reinstate');last=null;assert.equal((await lookupLib.findRenewalMember(lookup('name','Sample Member'),2026,2026)).status,'review');last=2026;
 records=[];await blocked(form(),/No matching registered member/);language='ms';await blocked(form(),/Tiada ahli berdaftar/);language='en';
 records=[row(),row({...person,memberNumber:'B-09-002'})];await blocked(form(),/use your MyKad/);
 records=[row()];last=2024;await blocked(form(),/lapsed/);last=null;await blocked(form(),/last active year/);last=2026;
 let f=form();f.delete('consent');await blocked(f,/consent/);limited=true;await blocked(form(),/Too many/);limited=false;dbFails=true;await blocked(form(),/could not save/);dbFails=false;
 f=form();f.set('email','forged@example.invalid');f.set('name','Forged name');f.set('rosterMemberNumber','B-09-999');assert.ok((await action.requestRenewal({},f)).success);let details=JSON.parse(writes.at(-1)[4]);assert.equal(details.email,person.email);assert.equal(details.name,person.name);assert.equal(details.rosterMemberNumber,person.memberNumber);assert.equal(details.addressLine,person.addressLine);
 assert.ok((await action.requestRenewal({},form('identity','900101-10-1234'))).success);assert.equal(writes.at(-1)[1],writes.at(-2)[1]);
 conflict=true;const before=mails;assert.ok((await action.requestRenewal({},form())).success);assert.equal(mails,before);
 records=[row({...person,lifetimeSince:2020})];last=2020;
 assert.equal((await lookupLib.findRenewalMember(lookup('name','Sample Member'),2026,2026)).status,'lifetime');
 assert.equal((await lookupLib.findRenewalMember(lookup('identity',person.identity),2027,2027)).status,'lifetime');
 const lifeBefore=[writes.length,mails,proofReads];assert.match((await action.requestRenewal({},form())).success,/lifetime/i);assert.deepEqual([writes.length,mails,proofReads],lifeBefore);
 console.log('PASS: lookup matching, lapse restrictions, stored details only, duplicate safety, and lifetime members require no renewal/payment or side effects. Mock data only.');
})().catch(e=>{console.error(e);process.exitCode=1;});
