'use client';
import {useUiText} from '../ui-language';

import {useActionState,useState} from 'react';
import {AddressFields} from '../address-fields';
import {requestMembership} from './actions';
export function JoinForm({bm}:{bm:boolean}){
 const ui = useUiText();

 const [state,action,pending]=useActionState(requestMembership,{});const [kind,setKind]=useState('mykad');const t=(en:string,ms:string)=>bm?ms:en;
 if(state.success)return <div className="shop-note" role="status"><h2>{t('Request received','Permohonan diterima')}</h2><p>{ui(state.success)}</p><a href="/">{t('Back to home','Kembali ke laman utama')}</a></div>;
 return <form action={action} autoComplete="off"><fieldset disabled={pending}><label>{t('Full name as on MyKad / passport','Nama penuh seperti MyKad / pasport')}<input name="name" required maxLength={150} autoComplete="name"/></label><label>{t('Identification type','Jenis pengenalan')}<select name="identityType" value={kind} onChange={e=>setKind(e.target.value)}><option value="mykad">{ui("MyKad / IC — Malaysian / Warganegara Malaysia")}</option><option value="passport">{ui("Passport — Non-Malaysian / Pasport — Bukan warganegara")}</option></select></label><label>{kind==='mykad'?t('MyKad / IC number (12 digits)','Nombor MyKad / KP (12 digit)'):t('Passport number','Nombor pasport')}<input key={kind} name="identity" required maxLength={kind==='mykad'?14:20} inputMode={kind==='mykad'?'numeric':'text'} pattern={kind==='mykad'?'[0-9]{6}-?[0-9]{2}-?[0-9]{4}':'[A-Za-z0-9-]{5,20}'} autoComplete="off"/></label>{kind==='passport'?<label>{t('Passport issuing country','Negara pengeluar pasport')}<input name="country" required maxLength={80}/></label>:<input type="hidden" name="country" value="Malaysia"/>}<label>{t('Email address','Alamat e-mel')}<input type="email" name="email" required maxLength={254} autoComplete="email"/></label><label>{t('Mobile number (include country code)','Nombor telefon bimbit (sertakan kod negara)')}<input type="tel" name="phone" required maxLength={30} autoComplete="tel" placeholder="+60…"/></label><AddressFields bm={bm}/><div hidden><label>{ui("Website")}<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="shop-consent"><input type="checkbox" name="consent" value="yes" required/>{t('I have read the notice below and consent to KPKMM using these details to review my membership request and contact me. I confirm the information is accurate.','Saya telah membaca notis di bawah dan bersetuju KPKMM menggunakan maklumat ini untuk menyemak permohonan dan menghubungi saya. Saya mengesahkan maklumat ini adalah tepat.')}</label><button>{pending?t('Submitting…','Menghantar…'):t('Request to join','Hantar permohonan')}</button></fieldset>{state.error&&<p className="shop-error" role="alert">{ui(state.error)}</p>}</form>;
}
