import Image from "next/image";
import { getClubData } from "../lib/club-data";

const facebook = "https://www.facebook.com/people/Mini-Malaysia-KPKMM/100066226611735/";
const logo = "/KPKMM-logo-white-band.png";
const banner = "/480344529_938897448327800_71183251801792565_n.jpg";
const fallbackPhotos = ["https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85"];
export const dynamic = "force-dynamic";

export default async function Home() {
  const data = await getClubData();
  const featured = data.events[0];
  const gallery = data.moments.length ? data.moments.map((moment) => ({ url: moment.url, caption: moment.caption })) : fallbackPhotos.map((url, index) => ({ url, caption: ["Fire & wheel", "Club gathering", "On the road"][index] }));
  return <main>
    <nav className="nav"><a className="brand" href="#top"><Image src={logo} alt="KPKMM club logo" width={42} height={42} unoptimized />Kelab Peminat Kereta Mini Malaysia - KPKMM</a><div className="links"><a href="#notices">Notices</a><a href="#events">Archive</a><a href="#gallery">Gallery</a><a href="/admin">Admin</a></div><a className="join-small" href={facebook} target="_blank" rel="noreferrer">Facebook ↗</a></nav>
    <section className="hero" id="top" style={{ minHeight: "520px", paddingTop: "42px", paddingBottom: "42px" }}><div className="hero-copy"><p className="eyebrow">MALAYSIA&apos;S MINI-CAR COMMUNITY</p><div style={{ display: "flex", alignItems: "center", gap: "18px" }}><Image src={logo} alt="KPKMM club logo" width={176} height={176} unoptimized priority style={{ flexShrink: 0, width: "176px", height: "auto" }} /><h1 style={{ margin: 0 }}>Small cars.<br /><em>Big spirit.</em></h1></div><p className="lede">Kelab Peminat Kereta Mini Malaysia brings together people who love every compact curve, clever detail and memorable drive.</p><div className="hero-actions"><a className="button" href="#events">Club archive <b>→</b></a></div></div><div className="hero-art" style={{ minHeight: "330px", transform: "scaleX(1.1)", transformOrigin: "right center" }}><Image src={banner} alt="KPKMM members at Mesyuarat Agung" fill sizes="(max-width: 760px) 100vw, 45vw" priority style={{ objectFit: "cover" }} /><div className="banner-wash" /><p>KPKMM TOGETHER</p></div></section>
    <section className="notices notice-top" id="notices"><div className="section-heading"><div><p className="eyebrow">STAY IN THE LOOP</p><h2>Notice board</h2></div></div><div className="notice-list">{data.notices.map((notice) => <article className="notice" key={notice.id}><time>{notice.date}</time><div><h3>{notice.title}</h3><p>{notice.details}</p></div><span>↗</span></article>)}</div></section>
    <section className="intro"><p className="eyebrow">ONE CLUB, MANY STORIES</p><h2>A welcoming home for people who believe the best memories begin with a turn of the key.</h2><a href="#gallery" className="arrow-link">See shared moments <b>→</b></a></section>
    <section className="events" id="events"><div className="section-heading"><div><p className="eyebrow">ON THE ROAD</p><h2>Club archive</h2></div></div>{featured && <article className="featured-event"><div className="event-date"><span>{featured.date.split(" ")[0]}</span><small>{featured.date.split(" ").slice(1).join(" ")}</small></div><div><p className="event-type">CLUB OUTING</p><h3>{featured.title}</h3><p>{featured.details}</p></div><a href="#gallery" className="round-arrow" aria-label="See outing photographs">→</a></article>}<div className="event-strip"><span>More routes. More stories. More friends.</span><span>More routes. More stories. More friends.</span></div></section>
    <section className="gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">SHARED MOMENTS</p><h2>Outings, captured</h2></div></div><div className="gallery-grid">{gallery.slice(0, 9).map((photo, index) => <figure className={`photo p${(index % 6) + 1}`} key={`${photo.url}-${index}`}><Image className="fb-image" src={photo.url} alt={`KPKMM outing — ${photo.caption}`} fill sizes="(max-width: 720px) 50vw, 33vw" unoptimized /><figcaption><strong>{photo.caption}</strong><span>KPKMM shared moment</span></figcaption></figure>)}</div></section>
    <section className="join"><p className="eyebrow">YOUR SEAT IS WAITING</p><h2>Come drive with us.</h2><p>Interested in joining KPKMM or partnering on an event? Get in touch and be part of the journey.</p><p><a className="button" href="mailto:kelabpeminatkeretaminimalaysia@gmail.com">Email us <b>→</b></a> <a className="text-link" href="tel:+60182262000">Call 018-226 2000</a></p></section>
    <footer><a className="brand" href="#top"><Image src={logo} alt="KPKMM club logo" width={42} height={42} unoptimized />Kelab Peminat Kereta Mini Malaysia - KPKMM</a><p>Kelab Peminat Kereta Mini Malaysia</p><a href="/admin">Admin portal →</a></footer>
  </main>;
}
