import { getLanguage } from "./language";
import Image from "next/image";
import { MomentGallery } from "./album-ui";
import { getClubData } from "../lib/club-data";

const facebook = "https://www.facebook.com/people/Mini-Malaysia-KPKMM/100066226611735/";
const logo = "/KPKMM-logo-white-band.png";
const banner = "/480344529_938897448327800_71183251801792565_n.jpg";
const fallbackPhotos = ["https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85"];
export const dynamic = "force-dynamic";

export default async function Home() {
  const lang = await getLanguage();
  const t = (en: string, ms: string) => lang === "ms" ? ms : en;
  const data = await getClubData();
  const gallery = data.moments.length ? data.moments : fallbackPhotos.map((url, index) => ({ id: "sample-" + index, url, caption: ["Fire & wheel", "Club gathering", "On the road"][index] }));
  return <main>
    <nav className="nav"><a className="brand" href="#top"><Image src={logo} alt="KPKMM club logo" width={42} height={42} unoptimized />Kelab Peminat Kereta Mini Malaysia - KPKMM</a><div className="links"><a href="#notices">{t("Notices","Notis")}</a><a href="#events">{t("Archive","Arkib")}</a><a href="#gallery">{t("Gallery","Galeri")}</a><a href="/admin">{t("Admin","Pentadbir")}</a></div><a className="join-small" href={facebook} target="_blank" rel="noreferrer">Facebook ↗</a></nav>
    <section className="hero" id="top" style={{ minHeight: "520px", paddingTop: "42px", paddingBottom: "42px" }}><div className="hero-copy"><p className="eyebrow">{t("MALAYSIA'S MINI-CAR COMMUNITY","KOMUNITI PEMINAT MINI MALAYSIA")}</p><div style={{ display: "flex", alignItems: "center", gap: "18px" }}><Image src={logo} alt="KPKMM club logo" width={176} height={176} unoptimized priority style={{ flexShrink: 0, width: "176px", height: "auto" }} /><h1 style={{ margin: 0 }}>{t("Small cars.","Kereta kecil.")}<br /><em>{t("Big spirit.","Semangat besar.")}</em></h1></div><p className="lede">{t("Kelab Peminat Kereta Mini Malaysia brings together people who love every compact curve, clever detail and memorable drive.","Kelab Peminat Kereta Mini Malaysia menyatukan peminat yang menghargai setiap keunikan Mini dan kenangan indah dalam setiap perjalanan.")}</p><div className="hero-actions"><a className="button" href="#events">{t("Club archive","Arkib kelab")} <b>→</b></a></div></div><div className="hero-art" style={{ minHeight: "330px", transform: "scaleX(1.1)", transformOrigin: "right center" }}><Image src={banner} alt="KPKMM members at Mesyuarat Agung" fill sizes="(max-width: 760px) 100vw, 45vw" priority style={{ objectFit: "cover" }} /><div className="banner-wash" /><p>{t("KPKMM TOGETHER","BERSAMA KPKMM")}</p></div></section>
    <section className="notices notice-top" id="notices"><div className="section-heading"><div><p className="eyebrow">{t("STAY IN THE LOOP","IKUTI PERKEMBANGAN")}</p><h2>{t("Notice board","Papan notis")}</h2></div></div><div className="notice-list">{data.notices.map((notice) => <article className="notice" key={notice.id}><time>{notice.date}</time><div><h3>{notice.title}</h3><p>{notice.details}</p>{notice.posterUrl && <img src={notice.posterUrl} alt={notice.title + " poster"} style={{ width: "100%", maxWidth: 260, height: "auto", marginTop: 12 }} />}</div><span>↗</span></article>)}</div></section>
    <section className="intro"><p className="eyebrow">{t("ONE CLUB, MANY STORIES","SATU KELAB, PELBAGAI KISAH")}</p><h2>{t("A welcoming home for people who believe the best memories begin with a turn of the key.","Tempat untuk semua yang percaya bahawa kenangan terindah bermula dengan satu perjalanan.")}</h2><a href="#gallery" className="arrow-link">{t("See shared moments","Lihat kenangan bersama")} <b>→</b></a></section>
    <section className="events" id="events"><div className="section-heading"><div><p className="eyebrow">{t("ON THE ROAD","DALAM PERJALANAN")}</p><h2>{t("Club archive","Arkib kelab")}</h2></div></div>{data.events.map((event) => { const linkedPhotos = data.moments.filter((moment) => moment.eventId === event.id); return <article className="featured-event" key={event.id}><div className="event-date"><span>{event.date.split(" ")[0]}</span><small>{event.date.split(" ").slice(1).join(" ")}</small></div><div><p className="event-type">{t("CLUB OUTING","AKTIVITI KELAB")}</p><h3>{event.title}</h3><p>{event.details}</p>{linkedPhotos.length > 0 && <p><strong>{linkedPhotos.length} {t(linkedPhotos.length === 1 ? "photo linked to this outing" : "photos linked to this outing", "foto dikaitkan dengan aktiviti ini")}</strong></p>}</div><a href="#gallery" className="round-arrow" aria-label={t("See outing photographs", "Lihat foto aktiviti")}>→</a></article>; })}{data.events.length === 0 && <p>{t("No club archives have been added yet.","Belum ada arkib kelab ditambahkan.")}</p>}<div className="event-strip"><span>{t("More routes. More stories. More friends.","Lebih banyak destinasi. Lebih banyak kisah. Lebih ramai sahabat.")}</span><span>{t("More routes. More stories. More friends.","Lebih banyak destinasi. Lebih banyak kisah. Lebih ramai sahabat.")}</span></div></section>
    <section className="gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">{t("SHARED MOMENTS","KENANGAN BERSAMA")}</p><h2>{t("Outings, captured","Kenangan perjalanan")}</h2></div></div><MomentGallery photos={gallery} events={data.events} lang={lang} /></section>
    <section className="join"><p className="eyebrow">{t("YOUR SEAT IS WAITING","TEMPAT ANDA MENANTI")}</p><h2>{t("Come drive with us.","Jom memandu bersama.")}</h2><p>{t("Interested in joining KPKMM or partnering on an event? Get in touch and be part of the journey.","Berminat untuk menyertai KPKMM atau bekerjasama dalam aktiviti kelab? Hubungi kami dan sertai perjalanan ini.")}</p><p><a className="button" href="mailto:kelabpeminatkeretaminimalaysia@gmail.com">{t("Email us","E-mel kami")} <b>→</b></a> <a className="text-link" href="tel:+60182262000">{t("Call 018-226 2000","Hubungi 018-226 2000")}</a></p></section>
    <footer><a className="brand" href="#top"><Image src={logo} alt="KPKMM club logo" width={42} height={42} unoptimized />Kelab Peminat Kereta Mini Malaysia - KPKMM</a><p>Kelab Peminat Kereta Mini Malaysia</p><a href="/admin">{t("Admin portal →","Portal pentadbir →")}</a></footer>
  </main>;
}
