import {redirect,notFound} from 'next/navigation';
import {db,isAdmin,uuid} from '../../../../lib/shop';
import {membershipReady,unseal} from '../../../../lib/membership';
import {reviewMembership} from '../../../join/actions';
import {ShopForm} from '../../../shop/forms';
import '../../../shop/shop.css';
export const dynamic='force-dynamic';
export const metadata={title:'Review membership | KPKMM',robots:{index:false,follow:false}};
export default async function Review({params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))redirect('/admin');const {id}=await params;if(!uuid(id))notFound();await membershipReady();const rows=await db()`SELECT * FROM club_applications WHERE id=${id}`;if(!rows.length)notFound();const row=rows[0];let person;try{person=unseal(row.payload);}catch{return <main className="shop"><p>Cannot decrypt this application. Check the server encryption key; do not overwrite the application.</p></main>;}return <main className="shop"><a href="/admin/members">← Requests / Permohonan</a><h1>{person.name}</h1><section className="shop-card"><p>Status: {row.status}</p><p>Email / E-mel: {person.email}</p><p>Mobile / Telefon: {person.phone}</p><p>{person.identityType==='mykad'?'MyKad / IC':'Passport / Pasport'}: ••••{person.identity.slice(-4)}</p><details><summary>Show full identification number / Paparkan nombor penuh</summary><p>{person.identity}</p></details><p>Country / Negara: {person.country}</p><p style={{whiteSpace:'pre-wrap'}}>Mailing address / Alamat surat-menyurat: {person.address}</p><p>Consent recorded / Persetujuan direkodkan: {new Date(row.created_at).toISOString().slice(0,10)} · {row.consent_version}</p></section><ShopForm action={reviewMembership} label="Save review / Simpan semakan"><input type="hidden" name="id" value={id}/><input type="hidden" name="previous" value={row.status}/><label>Decision / Keputusan<select name="status" defaultValue={row.status}><option value="pending">Pending / Menunggu</option><option value="approved">Approved / Diluluskan</option><option value="rejected">Rejected / Ditolak</option></select></label><p>No automatic email or member login is created. Contact the applicant separately. / Tiada e-mel atau akaun automatik. Hubungi pemohon secara berasingan.</p></ShopForm></main>;}
