'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import type {Celebration} from '../../../lib/celebrations';
export function CelebrationEditor({item,bm,action}:{item?:Celebration;bm:boolean;action:(f:FormData)=>Promise<boolean>}){
 const t=(en:string,ms:string)=>bm?ms:en,router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(true);setMessage('');try{
 const file=data.get('photo');if(file instanceof File&&file.size){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>20*1024*1024)throw Error();const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error();ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);let blob:Blob|null=null;for(const q of [.88,.7,.5,.3]){blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/webp',q));if(blob&&blob.size<=750*1024)break;}if(!blob||blob.size>750*1024)throw Error();data.set('photo',new File([blob],'celebration.webp',{type:'image/webp'}));}finally{bitmap.close();}}
 if(!await action(data))throw Error();setMessage(t('Saved.','Disimpan.'));if(!item)form.reset();router.refresh();
 }catch{setMessage(t('Could not save. Check the dates and image, or sign in again.','Tidak dapat menyimpan. Semak tarikh dan imej, atau log masuk semula.'));}finally{setBusy(false);}}
 return <section className="shop-card">{item&&<img src={item.url} alt={bm?item.ms:item.en} style={{width:'100%',maxHeight:220,objectFit:'contain'}}/>}<form onSubmit={submit}><fieldset disabled={busy}><input type="hidden" name="id" value={item?.id||''}/><label>{t('English greeting','Ucapan bahasa Inggeris')}<textarea name="en" required maxLength={300} defaultValue={item?.en}/></label><label>{t('Bahasa Malaysia greeting','Ucapan Bahasa Malaysia')}<textarea name="ms" required maxLength={300} defaultValue={item?.ms}/></label><label>{t('Banner / wish card','Sepanduk / kad ucapan')}<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required={!item}/></label><p>{t('JPG, PNG or WebP, up to 20 MB. Automatically compressed. Leave empty to keep the saved image.','JPG, PNG atau WebP, sehingga 20 MB. Dimampatkan secara automatik. Biarkan kosong untuk mengekalkan imej.')}</p><label>{t('Show from (Malaysia time)','Papar mulai (waktu Malaysia)')}<input type="date" name="starts" required defaultValue={item?.starts}/></label><label>{t('Show until (inclusive)','Papar sehingga (termasuk tarikh ini)')}<input type="date" name="ends" required defaultValue={item?.ends}/></label><label><input type="checkbox" name="enabled" value="yes" defaultChecked={item?.enabled??false}/>{t('Enable on homepage during these dates','Aktifkan di halaman utama pada tarikh ini')}</label><button>{busy?t('Saving…','Menyimpan…'):t('Save greeting','Simpan ucapan')}</button></fieldset></form>{item&&<form onSubmit={e=>{if(!confirm(t('Delete this greeting?','Padam ucapan ini?'))){e.preventDefault();return;}void submit(e);}}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="operation" value="delete"/><button disabled={busy}>{t('Delete greeting','Padam ucapan')}</button></form>}<p role="status">{message}</p></section>;
}
