import {savedFee} from '../../../../lib/membership-pricing';
import {MembershipPrice} from '../../../membership-price';
import {paymentPage} from '../../../../lib/enrolment';
import {getLanguage} from '../../../language';
import {ShopForm} from '../../../shop/forms';
import {uploadJoiningProof} from '../../enrolment-actions';
import '../../../shop/shop.css';
export const dynamic='force-dynamic';
export const metadata={title:'Membership payment | KPKMM',robots:{index:false,follow:false},referrer:'no-referrer' as const};
export default async function JoiningPayment({params}:{params:Promise<{token:string}>}){
 const {token}=await params,bm=(await getLanguage())==='ms',t=(en:string,ms:string)=>bm?ms:en;
 const row=await paymentPage(token);
 return <main className="shop" style={{maxWidth:760}}><h1>{t('Membership payment','Bayaran keahlian')}</h1>{!row||!row.valid?<p role="alert">{t('This private link is invalid or has expired. Contact the committee for a new link.','Pautan sulit tidak sah atau tamat tempoh. Hubungi jawatankuasa untuk pautan baharu.')}</p>:row.stage==='active'?<section className="shop-card"><h2>{t('Membership approved','Keahlian diluluskan')}</h2><p>{t('Your payment has been verified. Check your email for your welcome message and membership number.','Bayaran disahkan. Semak e-mel alu-aluan dan nombor ahli anda.')}</p></section>:row.stage==='proof_submitted'?<section className="shop-card"><h2>{t('Payment proof received','Bukti bayaran diterima')}</h2><p>{t('Awaiting committee verification. You do not need to upload again. Membership is not active yet.','Menunggu pengesahan jawatankuasa. Anda tidak perlu memuat naik lagi. Keahlian belum aktif.')}</p></section>:<><p>{t('Application approved — payment verification is the final step. Keep this link private.','Permohonan diluluskan — pengesahan bayaran ialah langkah terakhir. Simpan pautan ini secara sulit.')}</p><section className="shop-card"><MembershipPrice quote={savedFee(row.fee_quote,'new')} bm={bm}/><p>{t('Membership year','Tahun keahlian')}: {row.membership_year} · {t('Ends 31 December','Tamat 31 Disember')} {row.membership_year}</p><p>Maybank<br/>Kelab Peminat Kereta Mini Malaysia<br/><strong>5123 4360 5508</strong></p><p>{t('If you have already paid, do not pay again. Upload the existing receipt.','Jika sudah membayar, jangan bayar lagi. Muat naik resit sedia ada.')}</p></section><section className="shop-card"><ShopForm action={uploadJoiningProof} label={t('Submit payment proof','Hantar bukti bayaran')}><input type="hidden" name="token" value={token}/><label>{t('Payment proof — JPG, PNG or PDF, up to 700 KB','Bukti bayaran — JPG, PNG atau PDF, sehingga 700 KB')}<input required type="file" name="proof" accept="image/jpeg,image/png,application/pdf"/></label><p>{t('Your receipt is private and only available to authorised club administrators.','Resit anda sulit dan hanya boleh diakses oleh pentadbir kelab yang dibenarkan.')}</p></ShopForm></section></>}<p><a href="mailto:kelabpeminatkeretaminimalaysia@gmail.com">{t('Contact the committee','Hubungi jawatankuasa')}</a></p></main>;
}
