import { cookies } from 'next/headers';
import { notFound } from 'next/navigation';
import { db,ownsOrder,money,type Order } from '../../../../lib/shop';
import { getLanguage } from '../../../language';
import { ShopForm } from '../../forms';
import { uploadReceipt } from '../../actions';
import '../../shop.css';
export const dynamic='force-dynamic';
export const metadata={title:'Private order | KPKMM',robots:{index:false,follow:false}};
export default async function OrderPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; if(!(await ownsOrder(id)))notFound();
  const [order]=await db()<Order[]>`SELECT id,product_id,product_name,quantity,unit_price,customer_name,phone,status,created_at,receipt IS NOT NULL AS has_receipt FROM shop_orders WHERE id=${id}`;
  if(!order)notFound(); const bm=(await getLanguage())==='ms'; const t=(en:string,ms:string)=>bm?ms:en;
  const statuses:Record<string,string>={pending:t('Awaiting payment proof','Menunggu bukti bayaran'),review:t('Proof submitted — awaiting review','Bukti dihantar — menunggu semakan'),paid:t('Payment verified','Bayaran disahkan'),cancelled:t('Cancelled','Dibatalkan')};
  return <main className="shop"><a href="/shop">← {t('Marketplace','Kedai')}</a><h1>{t('Your order','Tempahan anda')}</h1><span className="shop-status">{statuses[order.status]}</span><section className="shop-card"><h2>{order.product_name}</h2><p>{order.quantity} × {money(order.unit_price)}</p><p className="shop-price">{t('Total','Jumlah')}: {money(order.quantity*order.unit_price)}</p><p>{order.customer_name} · {order.phone}</p><p>{t('Order reference','Rujukan tempahan')}: <code>{id}</code></p><details><summary>{t('Save your private access code','Simpan kod akses peribadi anda')}</summary><p>{t('Keep this reference and code to reopen your order on another device. Do not share them publicly.','Simpan rujukan dan kod ini untuk membuka tempahan pada peranti lain. Jangan kongsi secara terbuka.')}</p><code>{(await cookies()).get('shop-'+id)?.value}</code></details></section>{!['paid','cancelled'].includes(order.status)&&<><h2>{t('Bank transfer','Pindahan bank')}</h2><div className="bank-details"><strong>Maybank</strong><span>Kelab Peminat Kereta Mini Malaysia</span><strong>5123 4360 5508</strong><span>{t('Amount','Amaun')}: {money(order.quantity*order.unit_price)}</span><span>{t('Payment reference','Rujukan bayaran')}: {id.slice(0,8).toUpperCase()}</span></div><p>{t('Transfer the exact total. Your order is paid only after the club confirms receipt of funds.','Pindahkan jumlah tepat. Tempahan hanya dianggap dibayar selepas kelab mengesahkan penerimaan wang.')}</p><section className="shop-card"><h2>{t('Upload payment proof','Muat naik bukti bayaran')}</h2><p>{t('JPG, PNG or PDF, up to 700 KB. Crop or redact unrelated transactions and account balances before uploading. A new upload replaces your previous proof.','JPG, PNG atau PDF, maksimum 700 KB. Potong atau padam maklumat transaksi lain dan baki akaun sebelum memuat naik. Muat naik baharu menggantikan bukti terdahulu.')}</p><ShopForm action={uploadReceipt} label={t('Submit payment proof','Hantar bukti bayaran')}><input type="hidden" name="id" value={id}/><label>{t('Receipt file','Fail resit')}<input name="receipt" type="file" accept="image/jpeg,image/png,application/pdf" required/></label></ShopForm></section></>}{order.has_receipt&&<p><a className="shop-link" href={'/shop/orders/'+id+'/proof'}>{t('Download submitted proof','Muat turun bukti dihantar')}</a></p>}<p>{t('For order changes or cancellation, contact','Untuk perubahan atau pembatalan tempahan, hubungi')} <a href="tel:+60182262000">018-226 2000</a>.</p></main>;
}
