'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import type {Banner} from '../../../lib/banner';
export function BannerEditor({banner,action}:{banner:Banner;action:(form:FormData)=>Promise<{error?:string}>}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setMessage('Preparing / Menyediakan…');try{const data=new FormData(form);const file=data.get('photo');if(file instanceof File&&file.size){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>40*1024*1024)throw Error('Choose a JPG, PNG or WebP under 40 MB.');const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas');const scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('Cannot prepare image.');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);let compressed:Blob|null=null;for(const quality of [.82,.65,.45,.3]){compressed=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(compressed&&compressed.size<=750*1024)break;}if(!compressed||compressed.size>750*1024)throw Error('Please choose a smaller image.');data.set('photo',new File([compressed],'banner.jpg',{type:'image/jpeg'}));}finally{bitmap.close();}}const result=await action(data);if(result.error)throw Error(result.error);setMessage('Saved. / Disimpan.');form.reset();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save. Please try again.');}finally{setBusy(false);}}
 return <><img src={banner.url} alt="Current homepage banner" style={{width:'100%',maxWidth:700,aspectRatio:'2.4',objectFit:'cover',objectPosition:banner.position,borderRadius:20}}/><form onSubmit={submit}><fieldset disabled={busy}><label>Replace photo / Ganti foto<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/></label><p>Leave empty to keep the current photo. Photos are compressed automatically.</p><label>English caption<input name="en" maxLength={100} defaultValue={banner.en}/></label><label>Kapsyen Bahasa Malaysia<input name="ms" maxLength={100} defaultValue={banner.ms}/></label><label>Photo focus / Fokus foto<select name="position" defaultValue={banner.position}><option value="top">Top / Atas</option><option value="center">Centre / Tengah</option><option value="bottom">Bottom / Bawah</option></select></label><button>{busy?'Saving… / Menyimpan…':'Save banner / Simpan sepanduk'}</button></fieldset></form><form onSubmit={e=>{if(!window.confirm('Restore the original group photo and captions? / Pulihkan foto dan kapsyen asal?')){e.preventDefault();return;}void submit(e);}}><input type="hidden" name="reset" value="1"/><button disabled={busy}>Restore original / Pulihkan asal</button></form><p role="status">{message}</p></>;
}
